[tool.poetry]
name = "app"
version = "0.0.1"
description = ""
authors = []

[tool.poetry.dependencies]
python = ">=3.13,<3.14"
mylib = { path = "../mylib", develop = true }

[tool.poetry.group.dev.dependencies]
pyright = "1.1.407"
ruff = "0.14.5"

[tool.pyright]
extraPaths = ["../mylib"]
