[tool.poetry]
name = "mylib"
version = "0.0.1"
description = ""
authors = []

[tool.poetry.dependencies]
python = ">=3.13,<3.14"
numpy = "2.2.4"

[tool.poetry.group.dev.dependencies]
pyright = ">=1.1.392"
ruff = ">=0.7.2"
